/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EUsuario;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

import negocio.NUsuario;

public class LoginUsuario extends javax.swing.JInternalFrame {
    
    JMenu _Menu1;
    JMenu _Menu2;
    JDesktopPane _pnlPrincipal;
    public static EUsuario _EUsuario;
    
    public LoginUsuario() {
        initComponents();
        cmdEntrar.setText("Cadastrar");
        txtSenha.addActionListener(action);
        cmdEntrar.addActionListener(action);
        
    }

    public LoginUsuario(JMenu mnu1, JMenu mnu2, JDesktopPane pnlPrincipal) {
        
        this();
        _Menu1 = mnu1;
        _Menu2 = mnu2;
        _pnlPrincipal = pnlPrincipal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdEntrar = new javax.swing.JButton();
        cmdCadastro = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Bem-Vindo");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));

        cmdEntrar.setText("Entrar");
        getContentPane().add(cmdEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 90, -1));

        cmdCadastro.setText("Cadastrar");
        cmdCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 90, 30));

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 280, -1));
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 280, -1));

        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (!txtSenha.getText().isEmpty()) {
            cmdEntrar.setText("Entrar");
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void cmdCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCadastroActionPerformed
        try {
            
            txtMail.setText("");
            txtSenha.setText("");
            
            CadastroUsuario cadastroUsuario = new CadastroUsuario(_Menu1, _Menu1);
            this._pnlPrincipal.add(cadastroUsuario);
            cadastroUsuario.setVisible(true);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
    }//GEN-LAST:event_cmdCadastroActionPerformed

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
        
    }//GEN-LAST:event_jLabel6KeyPressed

    
    Action action = new AbstractAction(){
        @Override
        public void actionPerformed(ActionEvent e){
            try {
            NUsuario nUsuario = new NUsuario();
            
            if (cmdEntrar.getText().equals("Entrar") && !txtSenha.getText().isEmpty()) {
                
                if (nUsuario.ValidarLogin(txtMail.getText(), txtSenha.getText())) {
                    _EUsuario = nUsuario.BuscarPorEmail(txtMail.getText());
                    _Menu1.setEnabled(true);
                    _Menu2.setEnabled(true);
                    dispose();
                }
            } else {
                
                JOptionPane.showMessageDialog(rootPane,"Digite uma Senha");
                
            }
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    };
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCadastro;
    private javax.swing.JButton cmdEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
